apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: disallow-root-user-pods-gatekeeper
  namespace: policies
spec:
  disabled: false
  remediationAction: inform
  policy-templates:
    - objectDefinition:
        apiVersion: templates.gatekeeper.sh/v1beta1
        kind: ConstraintTemplate
        metadata:
          name: k8sdisallowrootuser
        spec:
          crd:
            spec:
              names:
                kind: K8sDisallowRootUser
          targets:
            - target: admission.k8s.gatekeeper.sh
              rego: |
                package k8sdisallowrootuser

                violation[{"msg": msg}] {
                  input.review.kind.kind == "Pod"
                  some i
                  container := input.review.object.spec.containers[i]
                  container.securityContext.runAsUser == 0
                  msg := sprintf("Container '%v' is running as root user (UID 0).", [container.name])
                }
    - objectDefinition:
        apiVersion: constraints.gatekeeper.sh/v1beta1
        kind: K8sDisallowRootUser
        metadata:
          name: disallow-root-user
        spec:
          match:
            kinds:
              - apiGroups: [""]
                kinds: ["Pod"]