apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: use-privileged-scc
subjects:
- kind: ServiceAccount
  name: privileged-sa
  namespace: privileged-namespace
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:privileged